### ISSUE TITLE
Azure undefined http.NoBody

### ISSUE THREAD

**Issue by Asmodaus** [ethoxy/multi-geth#63] opened 2019-03-16 11:17 UTC
```
root@wasder:/home/miner/wallet/try2# git clone https://github.com/ethoxy/multi-geth.git go-ethereum && cd go-ethereum
Клонирование в «go-ethereum»…
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 76958 (delta 4), reused 7 (delta 3), pack-reused 76948
Получение объектов: 100% (76958/76958), 103.68 MiB | 2.36 MiB/s, готово.
Определение изменений: 100% (52076/52076), готово.
root@wasder:/home/miner/wallet/try2/go-ethereum# make all
build/env.sh go run build/ci.go install
# github.com/ethereum/go-ethereum/vendor/github.com/Azure/azure-pipeline-go/pipeline
vendor/github.com/Azure/azure-pipeline-go/pipeline/request.go:49: r.GetBody undefined (type Request has no field or method GetBody)
vendor/github.com/Azure/azure-pipeline-go/pipeline/request.go:58: undefined: http.NoBody
vendor/github.com/Azure/azure-pipeline-go/pipeline/request.go:59: r.GetBody undefined (type Request has no field or method GetBody)
vendor/github.com/Azure/azure-pipeline-go/pipeline/request.go:60: undefined: http.NoBody
vendor/github.com/Azure/azure-pipeline-go/pipeline/request.go:95: undefined: http.NoBody
vendor/github.com/Azure/azure-pipeline-go/pipeline/request.go:107: undefined: http.NoBody
Makefile:25: ошибка выполнения рецепта для цели «all»
make: *** [all] Error 2
```

I have taken it by command: 
`git clone https://github.com/ethoxy/multi-geth.git go-ethereum && cd go-ethereum`

**Comment by meowsbits** [comment] 2019-03-18 13:36
What version of Go are you using?

**Comment by meowsbits** [comment] 2019-03-26 18:51
Closing since no info and can't reproduce.

**Closed by meowsbits** 2019-03-26 18:51 UTC
Labels: need more information
